package cn.jbolt.common.model;

import java.util.List;

import cn.jbolt.common.model.base.BaseUser;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	//建议将dao放在Service中只用作查询 
	public static final User dao = new User().dao();
	//在Service中声明 可直接复制过去使用
	//private User dao = new User().dao();
	public List<User> findByUserAndPwd(String name,String password){
		System.out.println("dddd");
		return dao.find("select * from user where username = '"
					+name+"' or phone = '"+name+"' and pwd = '"+password+"'");
	}
}
